AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Description: Weather Data Pipeline

Globals:
  Function:
    Timeout: 30
    MemorySize: 256
    Runtime: python3.13

Resources:
  WeatherPipelineFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: main.lambda_handler
      
  
      Policies:
      - S3WritePolicy:
            BucketName: weather-pipeline-2026
      
      Environment:
        Variables:
          AWS_BUCKET_NAME: weather-pipeline-2026